<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">


    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="HandheldFriendly" content="true">

    <title>Push Notification Services</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/desktop.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- jQuery -->
    <!--<script src="js/jquery.min.js"></script>-->

   <script src="jquery-ui-1.10.3/jquery-1.9.1.js"></script>
   <script src="js/bootstrap.js"></script>
   <link rel="stylesheet" href="jquery-ui-1.10.3/themes/base/jquery.ui.all.css">
   <script src="jquery-ui-1.10.3/ui/jquery.ui.core.js"></script>
   <script src="jquery-ui-1.10.3/ui/jquery.ui.widget.js"></script>
   <script src="jquery-ui-1.10.3/ui/jquery.ui.datepicker.js"></script>
   <script src="jquery-ui-1.10.3/ui/jquery.ui.menu.js"></script>
   <script src="jquery-ui-1.10.3/ui/jquery.ui.autocomplete.js"></script>
   <script src="jquery-ui-1.10.3/ui/jquery.ui.dialog.js"></script>
   <script src='https://www.google.com/recaptcha/api.js'></script>

   <script src="js/jscolor.js"></script>

  <script type="text/javascript" src="js/jquery.timepicker.js"></script>
  <link rel="stylesheet" type="text/css" href="css/jquery.timepicker.css" />
  <script type="text/javascript" src="js/tinymce/tinymce.min.js"></script>


</head>
<body>

<?php
if ($check_login == "TRUE") {
  ?>
  <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="index.php">Home</a></li>
            <li><a href="index.php?action=push">Apple Push</a></li>
            <li><a href="index.php?action=manage">Android Push</a></li>

            <?php
            if ($settings[9] == "Yes") {
              ?>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
              <ul class="dropdown-menu">
              <li><a href="index.php?action=new_push_site">Create New Push Site</a></li>
              <li><a href="index.php?action=manage">Manage Push Sites</a></li>
              </ul>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Templates <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="index.php?action=get_template_block&id=10">General Template</a></li>
                <li><a href="index.php?action=get_template_block&id=11">Header Template</a></li>
                <li><a href="index.php?action=get_template_block&id=12">App Name Template</a></li>
                <li><a href="index.php?action=get_template_block&id=13">Page Template</a></li>
                <li><a href="index.php?action=get_template_block&id=14">Menu Template</a></li>
                <li><a href="index.php?action=get_template_block&id=15">Area Template</a></li>
                <li><a href="index.php?action=get_template_block&id=16">Buttons Template</a></li>
                <li><a href="index.php?action=get_template_block&id=17">Delete/Cancel Template</a></li>
                <li><a href="index.php?action=get_template_block&id=18">Drop Down Template</a></li>

                <!--<li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>-->
              </ul>
            </li>

            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Analytics <span class="caret"></span></a>
              <ul class="dropdown-menu">
              <li><a href="index.php?action=reports&type=consumers">Consumer</a></li>
              <li><a href="index.php?action=reports&type=loyalty_stamps">Loyalty Stamps</a></li>
              <li><a href="#">Loyalty Awards</a></li>
              <li><a href="#">Coupons</a></li>
              <li><a href="#">Ecommerce</a></li>
              <li><a href="#">App Logs</a></li>
            </ul>
            </li>

            <?php
            }
            ?>


          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="active"><a href="mailto:support@theappwizards.com">Support <span class="sr-only">(current)</span></a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <?php
  }
  ?>

    <div class="container">
          <div class="jumbotron">
